default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: rede_social_development

test:
  <<: *default
  database: rede_social_test

production:
  <<: *default
  database: rede_social_production
  username: rede_social
  password: <%= ENV['REDE_SOCIAL_DATABASE_PASSWORD'] %>
